const data = [
  {
    title: "Senior Software Engineer PRO",
    companyName: "Tech Innovations",
    description:
      "Tech Innovations is seeking talented individuals to join our team and help shape the future of technology. As a leader in innovation, we offer exciting opportunities for growth and development. Join us and be part of a dynamic team dedicated to pushing the boundaries of what's possible.",
    address: "Hải Phòng",
    images: [
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/njyrgn2tpqisf5vnudnq.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/g8pjhnpjddyys9pqhips.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/gbbaiyrmudwbjzkueqxa.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/ggikmpq62gf16vxecymw.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/hibefcl8m9pnsheaebxk.svg",
    ],
    salary: "550",
    industries: ["Công nghệ thông tin", "Kế toán", "Nhân sự"],
    locations: ["Hà Nội", "Hồ Chí Minh"],
    positions: ["Thực tập sinh", "Nhân viên"],
    workTypes: ["Bán thời gian", "Toàn thời gian"],
    ownerId: "23d7d7cf-38c4-48be-95dc-6fb97af9780a",
  },
  {
    title: "Frontend Developer",
    companyName: "WebTech Solutions",
    description:
      "WebTech Solutions is in search of creative minds to join our frontend development team. As a key player in web technology, we offer an innovative environment for honing your skills. Join us and craft captivating user experiences that push the boundaries of the web.",
    address: "Hải Phòng",
    images: [
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/njyrgn2tpqisf5vnudnq.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/g8pjhnpjddyys9pqhips.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/ggikmpq62gf16vxecymw.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/gbbaiyrmudwbjzkueqxa.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/hibefcl8m9pnsheaebxk.svg",
    ],
    salary: "500",
    industries: ["Công nghệ thông tin", "Kế toán", "Nhân sự"],
    locations: ["Hà Nội", "Hồ Chí Minh"],
    positions: ["Thực tập sinh", "Nhân viên"],
    workTypes: ["Bán thời gian", "Toàn thời gian"],
    ownerId: "23d7d7cf-38c4-48be-95dc-6fb97af9780a",
  },
  {
    title: "Marketing Specialist",
    companyName: "MarketBoost Agency",
    description:
      "MarketBoost Agency is seeking passionate individuals to join our marketing team. As experts in boosting brand visibility, we provide a dynamic environment for unleashing your creativity. Join us and make an impact by crafting compelling marketing strategies.",
    address: "Hải Phòng",
    images: [
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/gbbaiyrmudwbjzkueqxa.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/njyrgn2tpqisf5vnudnq.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/ggikmpq62gf16vxecymw.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/hibefcl8m9pnsheaebxk.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/g8pjhnpjddyys9pqhips.svg",
    ],
    salary: "450",
    industries: ["Công nghệ thông tin", "Kế toán", "Nhân sự"],
    locations: ["Hà Nội", "Hồ Chí Minh"],
    positions: ["Thực tập sinh", "Nhân viên"],
    workTypes: ["Bán thời gian", "Toàn thời gian"],
    ownerId: "23d7d7cf-38c4-48be-95dc-6fb97af9780a",
  },
  {
    title: "UX/UI Designer",
    companyName: "DesignCraft Studios",
    description:
      "DesignCraft Studios is on the lookout for talented designers to join our UX/UI team. As leaders in design innovation, we provide an inspiring environment for unleashing your creativity. Join us and craft visually stunning experiences that captivate users.",
    address: "Hải Phòng",
    images: [
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/g8pjhnpjddyys9pqhips.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/njyrgn2tpqisf5vnudnq.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/ggikmpq62gf16vxecymw.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/hibefcl8m9pnsheaebxk.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/gbbaiyrmudwbjzkueqxa.svg",
    ],
    salary: "550",
    industries: ["Công nghệ thông tin", "Kế toán", "Nhân sự"],
    locations: ["Hà Nội", "Hồ Chí Minh"],
    positions: ["Thực tập sinh", "Nhân viên"],
    workTypes: ["Bán thời gian", "Toàn thời gian"],
    ownerId: "23d7d7cf-38c4-48be-95dc-6fb97af9780a",
  },
  {
    title: "Business Analyst",
    companyName: "BizStrat Solutions",
    description:
      "BizStrat Solutions is looking for analytical minds to join our business analysis team. As experts in strategic consulting, we provide a stimulating environment for analyzing complex business problems. Join us and drive actionable insights that shape the future of organizations.",
    address: "Hải Phòng",
    images: [
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/hibefcl8m9pnsheaebxk.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/g8pjhnpjddyys9pqhips.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/ggikmpq62gf16vxecymw.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/gbbaiyrmudwbjzkueqxa.svg",
      "https://res.cloudinary.com/djcamu6kz/image/upload/v1716748474/njyrgn2tpqisf5vnudnq.svg",
    ],
    salary: "600",
    industries: ["Công nghệ thông tin", "Kế toán", "Nhân sự"],
    locations: ["Hà Nội", "Hồ Chí Minh"],
    positions: ["Thực tập sinh", "Nhân viên"],
    workTypes: ["Bán thời gian", "Toàn thời gian"],
    ownerId: "23d7d7cf-38c4-48be-95dc-6fb97af9780a",
  },
];
